WIP

diff --git a/charts/jitsi-meet/values.yaml b/charts/jitsi-meet/values.yaml
--- a/charts/jitsi-meet/values.yaml
+++ b/charts/jitsi-meet/values.yaml
@@ -6,6 +6,90 @@ imagePullSecrets: []
 nameOverride: ""
 fullnameOverride: ""
 
+etherpad:
+  replicaCount: 1
+
+  image:
+    repository: etherpad/etherpad
+    tag: 1.8.0
+    pullPolicy: IfNotPresent
+
+  serviceAccount:
+    # Specifies whether a service account should be created
+    create: true
+    # Annotations to add to the service account
+    annotations: {}
+    # The name of the service account to use.
+    # If not set and create is true, a name is generated using the fullname template
+    name:
+
+  # Additional pod annotations (jicofo component)
+  podAnnotations: {}
+
+  # Additional pod labels (jicofo component)
+  podLabels: {}
+
+  podSecurityContext: {}
+    # fsGroup: 2000
+
+  securityContext: {}
+    # capabilities:
+    #   drop:
+    #   - ALL
+    # readOnlyRootFilesystem: true
+    # runAsNonRoot: true
+    # runAsUser: 1000
+
+  service:
+    type: ClusterIP
+    port: 9001
+
+  resources: {}
+    # We usually recommend not to specify default resources and to leave this as a conscious
+    # choice for the user. This also increases chances charts run on environments with little
+    # resources, such as Minikube. If you do want to specify resources, uncomment the following
+    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
+    # limits:
+    #   cpu: 200m
+    #   memory: 512Mi
+    # requests:
+    #   cpu: 50m
+    #   memory: 256Mi
+
+  nodeSelector: {}
+
+  tolerations: []
+
+  affinity: {}
+
+# --- settings.json.template.txt  2020-04-10 08:43:46.049151711 +0200
+# +++ settings.json2      2020-04-10 09:01:01.120323900 +0200
+# @@ -3,69 +3,14 @@
+# -  "title": "Etherpad",
+# +  "title": "Video Chat",
+
+# env TITLE
+
+# @@ -74,27 +19,7 @@
+# -  "defaultPadText" : "Welcome to Etherpad!\n\nThis pad text is synchronized as you type, so that everyone viewing this page sees the same text. This allows you to collaborate seamlessly on documents!\n\nGet involved with Etherpad at https:\/\/etherpad.org\n",
+# +  "defaultPadText": "Welcome to Web Chat!\n\n",
+
+
+# env DEFAULT_PAD_TEXT
+
+# @@ -190,35 +117,35 @@
+#    /*
+#     * Should we suppress errors from being visible in the default Pad Text?
+#     */
+# -  "suppressErrorsInPadText": false,
+# +  "suppressErrorsInPadText": true,
+
+# Pas de env dispo dans l'image Etherpad officielle
+
+# ADMIN_PASSWORD ?
+# USER_PASSWORD ?
+
+
 jibri:
   # XMPP recorder user for Jibri client connections
   recorderUser: recorder
@@ -21,6 +105,167 @@ jibri:
 
   # Name of existing Secret to use (jibri component)
   existingSecret: ""
+
+
+# {
+#     "recording_directory":"{{ .Env.JIBRI_RECORDING_DIR }}",
+#     // The path to the script which will be run on completed recordings
+#     "finalize_recording_script_path": "{{ .Env.JIBRI_FINALIZE_RECORDING_SCRIPT_PATH }}",
+#     "xmpp_environments": [
+#         {
+#             // A friendly name for this environment which can be used
+#             //  for logging, stats, etc.
+#             "name": "prod environment",
+#             // The hosts of the XMPP servers to connect to as part of
+#             //  this environment
+#             "xmpp_server_hosts": [
+#                 "{{ .Env.XMPP_SERVER }}"
+#             ],
+#             "xmpp_domain": "{{ .Env.XMPP_DOMAIN }}",
+#             // Jibri will login to the xmpp server as a privileged user
+#             "control_login": {
+#                 "domain": "{{ .Env.XMPP_AUTH_DOMAIN }}",
+#                 // The credentials for logging in
+#                 "username": "{{ .Env.JIBRI_XMPP_USER }}",
+#                 "password": "{{ .Env.JIBRI_XMPP_PASSWORD }}"
+#             },
+#             // Using the control_login information above, Jibri will join
+#             //  a control muc as a means of announcing its availability
+#             //  to provide services for a given environment
+#             "control_muc": {
+#                 "domain": "{{ .Env.XMPP_INTERNAL_MUC_DOMAIN }}",
+#                 "room_name": "{{ .Env.JIBRI_BREWERY_MUC }}",
+# 		// MUST be unic for every instanse
+#                 "nickname": "jibri-instanse-{{ .Env.JIBRI_INSTANCE_ID }}"
+#             },
+#             // All participants in a call join a muc so they can exchange
+#             //  information.  Jibri can be instructed to join a special muc
+#             //  with credentials to give it special abilities (e.g. not being
+#             //  displayed to other users like a normal participant)
+#             "call_login": {
+#                 "domain": "{{ .Env.XMPP_RECORDER_DOMAIN }}",
+#                 "username": "{{ .Env.JIBRI_RECORDER_USER }}",
+#                 "password": "{{ .Env.JIBRI_RECORDER_PASSWORD }}"
+#             },
+#             // When jibri gets a request to start a service for a room, the room
+#             //  jid will look like:
+#             //  roomName@optional.prefixes.subdomain.xmpp_domain
+#             // We'll build the url for the call by transforming that into:
+#             //  https://xmpp_domain/subdomain/roomName
+#             // So if there are any prefixes in the jid (like jitsi meet, which
+#             //  has its participants join a muc at conference.xmpp_domain) then
+#             //  list that prefix here so it can be stripped out to generate
+#             //  the call url correctly
+#             "room_jid_domain_string_to_strip_from_start": "{{ .Env.JIBRI_STRIP_DOMAIN_JID }}.",
+#             // The amount of time, in minutes, a service is allowed to continue.
+#             //  Once a service has been running for this long, it will be
+#             //  stopped (cleanly).  A value of 0 means an indefinite amount
+#             //  of time is allowed
+#             "usage_timeout": "0"
+#         }
+#     ]
+# }
+
+
+# handlers = java.util.logging.FileHandler, java.util.logging.ConsoleHandler
+
+# java.util.logging.FileHandler.level = FINE
+# java.util.logging.FileHandler.pattern   = {{ .Env.JIBRI_LOGS_DIR }}/log.%g.txt
+# java.util.logging.FileHandler.formatter = net.java.sip.communicator.util.ScLogFormatter
+# java.util.logging.FileHandler.count = 10
+# java.util.logging.FileHandler.limit = 10000000
+
+# org.jitsi.jibri.capture.ffmpeg.util.FfmpegFileHandler.level = FINE
+# org.jitsi.jibri.capture.ffmpeg.util.FfmpegFileHandler.pattern   = {{ .Env.JIBRI_LOGS_DIR }}/ffmpeg.%g.txt
+# org.jitsi.jibri.capture.ffmpeg.util.FfmpegFileHandler.formatter = net.java.sip.communicator.util.ScLogFormatter
+# org.jitsi.jibri.capture.ffmpeg.util.FfmpegFileHandler.count = 10
+# org.jitsi.jibri.capture.ffmpeg.util.FfmpegFileHandler.limit = 10000000
+
+# org.jitsi.jibri.sipgateway.pjsua.util.PjsuaFileHandler.level = FINE
+# org.jitsi.jibri.sipgateway.pjsua.util.PjsuaFileHandler.pattern   = {{ .Env.JIBRI_LOGS_DIR }}/pjsua.%g.txt
+# org.jitsi.jibri.sipgateway.pjsua.util.PjsuaFileHandler.formatter = net.java.sip.communicator.util.ScLogFormatter
+# org.jitsi.jibri.sipgateway.pjsua.util.PjsuaFileHandler.count = 10
+# org.jitsi.jibri.sipgateway.pjsua.util.PjsuaFileHandler.limit = 10000000
+
+# org.jitsi.jibri.selenium.util.BrowserFileHandler.level = FINE
+# org.jitsi.jibri.selenium.util.BrowserFileHandler.pattern   = {{ .Env.JIBRI_LOGS_DIR }}/browser.%g.txt
+# org.jitsi.jibri.selenium.util.BrowserFileHandler.formatter = net.java.sip.communicator.util.ScLogFormatter
+# org.jitsi.jibri.selenium.util.BrowserFileHandler.count = 10
+# org.jitsi.jibri.selenium.util.BrowserFileHandler.limit = 10000000
+
+# java.util.logging.ConsoleHandler.level = FINE
+# java.util.logging.ConsoleHandler.formatter = net.java.sip.communicator.util.ScLogFormatter
+
+# org.jitsi.level = FINE
+
+# org.glassfish.level = INFO
+# org.osgi.level = INFO
+
+
+
+# #!/usr/bin/with-contenv bash
+
+# if [[ -z $JIBRI_RECORDER_PASSWORD || -z $JIBRI_XMPP_PASSWORD ]]; then
+#     echo 'FATAL ERROR: Jibri recorder password and auth password must be set'
+#     exit 1
+# fi
+
+# OLD_JIBRI_RECORDER_PASSWORD=passw0rd
+# if [[ "$JIBRI_RECORDER_PASSWORD" == "$OLD_JIBRI_RECORDER_PASSWORD" ]]; then
+#     echo 'FATAL ERROR: Jibri recorder password must be changed, check the README'
+#     exit 1
+# fi
+
+# OLD_JIBRI_XMPP_PASSWORD=passw0rd
+# if [[ "$JIBRI_XMPP_PASSWORD" == "$OLD_JIBRI_XMPP_PASSWORD" ]]; then
+#     echo 'FATAL ERROR: Jibri auth password must be changed, check the README'
+#     exit 1
+# fi
+
+# # DISPLAY is necessary for start
+# [ -z "${DISPLAY}" ] \
+# && ( echo -e "\e[31mERROR: Please set DISPLAY variable.\e[39m"; kill 1; exit 1 )
+
+# # check loaded snd_aloop module and exit if is not loaded on the host
+# [ -z "$(lsmod | grep -om1 snd_aloop)" ] \
+# && ( echo -e "\e[31mERROR: Please load snd-aloop module on the docker host.\e[39m"; kill 1; exit 1 )
+
+# # get host's audio group id
+# host_audio_group="$(stat -c %g /dev/snd/pcmC0D0p)"
+# # try to create group with this id. If group with the id already exists, just skip
+# groupadd -g ${host_audio_group} jibri-audio >/dev/null 2>&1
+# # include user to the group by id
+# usermod -aG ${host_audio_group} jibri
+
+# # script for finalizing must have executing bit.
+# [ ! -z "${JIBRI_FINALIZE_RECORDING_SCRIPT_PATH}" ] \
+# && [ ! -x "${JIBRI_FINALIZE_RECORDING_SCRIPT_PATH}" ] \
+# && chmod +x ${JIBRI_FINALIZE_RECORDING_SCRIPT_PATH}
+
+# # set rundom jibri nickname for the instance if is not set
+# [ -z "${JIBRI_INSTANCE_ID}" ] && export JIBRI_INSTANCE_ID=$(date +%N)
+
+# # always recreate configs
+# tpl /defaults/config.json > /etc/jitsi/jibri/config.json
+# tpl /defaults/logging.properties > /etc/jitsi/jibri/logging.properties
+
+# # make recording dir
+# [ -z "${JIBRI_RECORDING_DIR}" ] && export JIBRI_RECORDING_DIR=/config/recordings
+# mkdir -p ${JIBRI_RECORDING_DIR}
+# chown -R jibri ${JIBRI_RECORDING_DIR}
+
+# # make logs dir
+# [ -z "${JIBRI_LOGS_DIR}" ] && export JIBRI_LOGS_DIR=/config/logs
+# mkdir -p ${JIBRI_LOGS_DIR}
+# chown -R jibri ${JIBRI_LOGS_DIR}
+
+
+# #!/usr/bin/with-contenv bash
+
+# DAEMON="/usr/bin/Xorg -nocursor -noreset  +extension RANDR +extension RENDER -logfile /tmp/xorg.log  -config /etc/jitsi/jibri/xorg-video-dummy.conf ${DISPLAY}"
+# exec s6-setuidgid jibri /bin/bash -c "exec $DAEMON"
+
+
 
 jicofo:
   replicaCount: 1
@@ -123,6 +368,110 @@ jigasi:
 
   # Name of existing Secret to use (jigasi component)
   existingSecret: ""
+
+
+# # SIP account
+# {{ if and .Env.JIGASI_SIP_PORT .Env.JIGASI_SIP_TRANSPORT }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.PROXY_ADDRESS={{ .Env.JIGASI_SIP_SERVER }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.PROXY_AUTO_CONFIG=false
+# net.java.sip.communicator.impl.protocol.sip.acc1.PROXY_PORT={{ .Env.JIGASI_SIP_PORT | default "5060" }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.PREFERRED_TRANSPORT={{ .Env.JIGASI_SIP_TRANSPORT | default "UDP" }}
+# {{ end }}
+# {{ if .Env.JIGASI_ENABLE_SDES_SRTP | default "0" | toBool }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.SDES_CIPHER_SUITES=AES_CM_128_HMAC_SHA1_80,AES_CM_128_HMAC_SHA1_32
+# {{ end }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.ACCOUNT_UID=SIP\:{{ .Env.JIGASI_SIP_URI }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.PASSWORD={{ .Env.JIGASI_SIP_PASSWORD | b64enc }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.PROTOCOL_NAME=SIP
+# net.java.sip.communicator.impl.protocol.sip.acc1.SERVER_ADDRESS={{ .Env.JIGASI_SIP_SERVER }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.USER_ID={{ .Env.JIGASI_SIP_URI }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.KEEP_ALIVE_INTERVAL=25
+# net.java.sip.communicator.impl.protocol.sip.acc1.KEEP_ALIVE_METHOD={{ .Env.JIGASI_SIP_KEEP_ALIVE_METHOD | default "OPTIONS" }}
+# net.java.sip.communicator.impl.protocol.sip.acc1.DOMAIN_BASE={{ .Env.XMPP_DOMAIN }}
+
+# # XMPP account used for control
+# net.java.sip.communicator.impl.protocol.jabber.acc1=acc1
+# net.java.sip.communicator.impl.protocol.jabber.acc1.ACCOUNT_UID=Jabber:{{ .Env.JIGASI_XMPP_USER }}@{{ .Env.XMPP_AUTH_DOMAIN }}
+# net.java.sip.communicator.impl.protocol.jabber.acc1.USER_ID={{ .Env.JIGASI_XMPP_USER }}@{{ .Env.XMPP_AUTH_DOMAIN }}
+# net.java.sip.communicator.impl.protocol.jabber.acc1.IS_SERVER_OVERRIDDEN=true
+# net.java.sip.communicator.impl.protocol.jabber.acc1.SERVER_ADDRESS={{ .Env.XMPP_SERVER }}
+# net.java.sip.communicator.impl.protocol.jabber.acc1.PASSWORD={{ .Env.JIGASI_XMPP_PASSWORD | b64enc }}
+# net.java.sip.communicator.impl.protocol.jabber.acc1.AUTO_GENERATE_RESOURCE=true
+# net.java.sip.communicator.impl.protocol.jabber.acc1.BREWERY={{ .Env.JIGASI_BREWERY_MUC }}@{{ .Env.XMPP_INTERNAL_MUC_DOMAIN }}
+# net.java.sip.communicator.impl.protocol.jabber.acc1.DOMAIN_BASE={{ .Env.XMPP_DOMAIN }}
+
+
+# org.jitsi.jigasi.HEALTH_CHECK_SIP_URI={{ .Env.JIGASI_HEALTH_CHECK_SIP_URI | default "" }}
+# org.jitsi.jigasi.HEALTH_CHECK_INTERVAL={{ .Env.JIGASI_HEALTH_CHECK_INTERVAL | default "300000" }}
+
+# org.jitsi.jigasi.xmpp.acc.IS_SERVER_OVERRIDDEN=true
+# org.jitsi.jigasi.xmpp.acc.SERVER_ADDRESS={{ .Env.XMPP_SERVER }}
+
+# {{ if .Env.ENABLE_AUTH | default "0" | toBool }}
+# org.jitsi.jigasi.xmpp.acc.USER_ID={{ .Env.JIGASI_XMPP_USER }}@{{ .Env.XMPP_AUTH_DOMAIN }}
+# org.jitsi.jigasi.xmpp.acc.PASS={{ .Env.JIGASI_XMPP_PASSWORD }}
+# {{ end }}
+
+
+# {{ if .Env.ENABLE_TRANSCRIPTIONS | default "0" | toBool }}
+# # Transcription config
+
+# org.jitsi.jigasi.transcription.BASE_URL={{ .Env.PUBLIC_URL }}/transcripts
+# org.jitsi.jigasi.transcription.jetty.port=-1
+# org.jitsi.jigasi.transcription.ADVERTISE_URL={{ .Env.JIGASI_TRANSCRIBER_ADVERTISE_URL | default "false"}}
+
+# org.jitsi.jigasi.transcription.SEND_TXT={{ .Env.JIGASI_TRANSCRIBER_SEND_TXT | default "false"}}
+# org.jitsi.jigasi.transcription.RECORD_AUDIO={{ .Env.JIGASI_TRANSCRIBER_RECORD_AUDIO | default "false"}}
+# {{end}}
+
+
+
+
+
+
+# if [[ -z $JIGASI_XMPP_PASSWORD ]]; then
+#     echo 'FATAL ERROR: Jigasi auth password must be set'
+#     exit 1
+# fi
+
+# # Create Google Cloud Credentials
+# if [[ $ENABLE_TRANSCRIPTIONS -eq 1 || $ENABLE_TRANSCRIPTIONS == "true" ]] && [[ ! -f /config/key.json ]]; then
+#     if [[ -z $GC_PROJECT_ID || -z $GC_PRIVATE_KEY_ID || -z $GC_PRIVATE_KEY || -z $GC_CLIENT_EMAIL || -z $GC_CLIENT_ID || -z $GC_CLIENT_CERT_URL ]]; then
+#         echo 'Transcriptions: One or more environment variables are undefined'
+#         exit 1
+#     fi
+
+#     jq -n \
+#         --arg GC_PROJECT_ID "$GC_PROJECT_ID" \
+#         --arg GC_PRIVATE_KEY_ID "$GC_PRIVATE_KEY_ID" \
+#         --arg GC_PRIVATE_KEY "$GC_PRIVATE_KEY" \
+#         --arg GC_CLIENT_EMAIL "$GC_CLIENT_EMAIL" \
+#         --arg GC_CLIENT_ID "$GC_CLIENT_ID" \
+#         --arg GC_CLIENT_CERT_URL "$GC_CLIENT_CERT_URL" \
+#         '{
+#             type: "service_account",
+#             project_id: $GC_PROJECT_ID,
+#             private_key_id: $GC_PRIVATE_KEY_ID,
+#             private_key: $GC_PRIVATE_KEY,
+#             client_email: $GC_CLIENT_EMAIL,
+#             client_id: $GC_CLIENT_ID,
+#             auth_uri: "https://accounts.google.com/o/oauth2/auth",
+#             token_uri: "https://oauth2.googleapis.com/token",
+#             auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs",
+#             client_x509_cert_url: $GC_CLIENT_CERT_URL
+#         }' \
+#         > /config/key.json
+# fi
+
+
+
+# JAVA_SYS_PROPS="-Djava.util.logging.config.file=/config/logging.properties"
+
+# DAEMON=/usr/share/jigasi/jigasi.sh
+# DAEMON_OPTS="--nocomponent=true --configdir=/ --configdirname=config --min-port=$JIGASI_PORT_MIN --max-port=$JIGASI_PORT_MAX"
+
+# exec s6-setuidgid jigasi /bin/bash -c "JAVA_SYS_PROPS=\"$JAVA_SYS_PROPS\" exec $DAEMON $DAEMON_OPTS"
+
 
 jvb:
   replicaCount: 1
